"use client";
import {useState,type FormEvent} from "react";
import {Box,Users,Plus,Pencil,Trash2,ShieldCheck,Database,LogOut} from "lucide-react";
import {toast} from "sonner";
import {Header,Footer} from "@/components/cubic-ui";
import {useCubic} from "@/components/cubic-data";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Checkbox} from "@/components/ui/checkbox";
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from "@/components/ui/alert-dialog";
import {memberSchema,robotSchema,type Member,type Robot} from "@/lib/content";
type Kind="members"|"robots";
const blankMember={name:"",role:"",bio:"",image:"",order:0};
const blankRobot={name:"",season:"",description:"",image:"",dimensions:"",weight:"",programming:"",materials:"",drivetrain:"",specs:[],featured:true,order:0};
export default function Admin(){
 const store=useCubic();const [tab,setTab]=useState("robots"),[edit,setEdit]=useState<{kind:Kind;value:Record<string,unknown>;id?:string}|null>(null),[deleting,setDeleting]=useState<{kind:Kind;id:string;name:string}|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState("");
 const open=(kind:Kind,item?:Member|Robot)=>{setFormError("");setEdit({kind,value:item?{...item}:kind==="members"?{...blankMember,order:store.members.length}:{...blankRobot,order:store.robots.length},id:item?.id});};
 const change=(key:string,value:unknown)=>setEdit(e=>e?{...e,value:{...e.value,[key]:value}}:e);
 async function submit(e:FormEvent){e.preventDefault();if(!edit||busy)return;setFormError("");const parsed=(edit.kind==="members"?memberSchema:robotSchema).safeParse(edit.value);if(!parsed.success){setFormError(parsed.error.issues[0].message);return;}setBusy(true);try{await store.save(edit.kind,parsed.data,edit.id);setEdit(null);toast.success("Saved to the team website.");}catch(e){setFormError(e instanceof Error?e.message:"Save failed. Your draft is still here.");}finally{setBusy(false);}}
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setFormError("");try{await store.login(email,password);setPassword("");}catch{setFormError("Sign-in failed. Check your email, password, and Firebase Authentication settings.");}finally{setBusy(false);}}
 function field(key:string,label:string,options:{required?:boolean;long?:boolean;type?:string;max?:number}={}){return <label className={options.long?"field full":"field"}><span>{label}{options.required&&" *"}</span>{options.long?<textarea rows={3} maxLength={options.max??2000} value={String(edit?.value[key]??"")} onChange={e=>change(key,e.target.value)}/>:<input required={options.required} type={options.type??"text"} min={options.type==="number"?0:undefined} max={options.type==="number"?9999:undefined} maxLength={options.max??300} value={String(edit?.value[key]??"")} onChange={e=>change(key,options.type==="number"?Number(e.target.value):e.target.value)}/>}</label>}
 return <><Header/><main className="wrap admin-main"><div className="admin-heading"><div><div className="eyebrow">CUBIC / TEAM WORKSPACE</div><h1>Make it yours.</h1><p>Your people. Your machines. All in one place.</p></div><a className="button" href="/">View website</a></div>
 {store.mode==="loading"&&<p role="status">Connecting to your team…</p>}
 {store.mode==="error"&&<div className="notice error" role="alert"><strong>Connection needs attention</strong><p>{store.error}</p></div>}
 {store.mode==="live"&&!store.user&&<form onSubmit={login} className="login-panel"><ShieldCheck/><div><h2>Administrator sign-in</h2><p>Use the account your team has approved in Firebase.</p></div><label className="field"><span>Email</span><input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>Password</span><input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button dark" disabled={busy}>{busy?"Signing in…":"Sign in"}</button>{formError&&<p className="error-text" role="alert">{formError}</p>}</form>}
 {store.user&&<div className="auth-strip"><span><ShieldCheck size={18}/>{store.user.email} · {!store.authReady?"Checking access…":store.isAdmin?"Administrator":"Read-only access"}</span><button className="text-button" onClick={()=>void store.logout().catch(()=>toast.error("Could not sign out. Try again."))}><LogOut size={15}/> Sign out</button></div>}
 {store.user&&store.authReady&&!store.isAdmin&&<p className="notice">This account is not an administrator. A project owner must add your Firebase user ID under admins in the database.</p>}
 <Tabs value={tab} onValueChange={setTab} className="admin-tabs"><TabsList><TabsTrigger value="robots"><Box size={16}/> Robots ({store.robots.length})</TabsTrigger><TabsTrigger value="members"><Users size={16}/> Members ({store.members.length})</TabsTrigger></TabsList>
 {(["robots","members"] as Kind[]).map(kind=><TabsContent value={kind} key={kind}><div className="admin-section-heading"><div><h2>{kind==="robots"?"The robot lab":"The team roster"}</h2><p>{kind==="robots"?"Add builds, define specifications, and choose your featured robots.":"Introduce the people who make Cubic happen."}</p></div><button className="button dark" onClick={()=>open(kind)} disabled={!store.isAdmin}><Plus size={17}/> Add {kind==="robots"?"robot":"member"}</button></div><div className="admin-list">{(kind==="robots"?store.robots:store.members).map(item=><article className="admin-row" key={item.id}><span className="row-symbol">{kind==="robots"?<Box size={22}/>:<Users size={22}/>}</span><div><h3>{item.name}</h3><p>{"role" in item?item.role:item.season||"Robot profile"}</p></div>{"featured" in item&&item.featured&&<span className="pill">FEATURED</span>}<span className="order-tag">Order {item.order}</span><div className="row-actions"><button aria-label={`Edit ${item.name}`} className="icon-button" onClick={()=>open(kind,item)} disabled={!store.isAdmin}><Pencil size={17}/></button><button aria-label={`Delete ${item.name}`} className="icon-button danger" onClick={()=>setDeleting({kind,id:item.id,name:item.name})} disabled={!store.isAdmin}><Trash2 size={17}/></button></div></article>)}{!(kind==="robots"?store.robots:store.members).length&&<div className="empty-state"><p>No {kind} yet. Add your first {kind==="robots"?"robot":"member"} to get started.</p></div>}</div></TabsContent>)}
 </Tabs><div className="admin-footnote"><Database size={15}/>{store.mode==="live"?"Connected to Firebase Realtime Database. Saved changes appear on the website automatically.":"Firebase setup includes public profile reads and writes restricted to approved administrators."}</div></main><Footer/>
 <Dialog open={!!edit} onOpenChange={open=>{if(!open&&!busy)setEdit(null);}}><DialogContent className="editor-dialog" onInteractOutside={e=>e.preventDefault()}><DialogTitle>{edit?.id?"Edit":"Add"} {edit?.kind==="members"?"member":"robot"}</DialogTitle><DialogDescription>Saved changes will appear on the website immediately.</DialogDescription>{edit&&<form onSubmit={submit}><fieldset disabled={busy} className="form-grid">{field("name",edit.kind==="members"?"Name":"Robot name",{required:true,max:100})}{edit.kind==="members"?field("role","Role / subteam",{required:true,max:100}):field("season","Season / build label",{max:50})}{field("image","Photo URL",{max:2000})}{field("order","Display order",{type:"number"})}{edit.kind==="members"?field("bio","Short bio",{long:true,max:1500}):<>{field("description","About this robot",{long:true})}{field("dimensions","Size / dimensions",{max:100})}{field("weight","Weight",{max:100})}{field("programming","Programming languages & tools",{})}{field("materials","Materials",{})}{field("drivetrain","Drivetrain",{max:200})}<div className="field"><span>Homepage placement</span><label className="check-label"><Checkbox checked={edit.value.featured===true} onCheckedChange={v=>change("featured",v===true)}/> Feature on homepage</label></div><div className="full custom-specs"><div><strong>Additional specifications</strong><button type="button" className="text-button" disabled={(edit.value.specs as Robot["specs"]).length>=20} onClick={()=>change("specs",[...edit.value.specs as Robot["specs"],{label:"",value:""}])}><Plus size={15}/> Add specification</button></div>{(edit.value.specs as Robot["specs"]).map((spec,i)=><div className="custom-spec-row" key={i}><input aria-label={`Specification ${i+1} label`} required maxLength={80} value={spec.label} onChange={e=>change("specs",(edit.value.specs as Robot["specs"]).map((s,j)=>j===i?{...s,label:e.target.value}:s))}/><input aria-label={`Specification ${i+1} value`} required maxLength={300} value={spec.value} onChange={e=>change("specs",(edit.value.specs as Robot["specs"]).map((s,j)=>j===i?{...s,value:e.target.value}:s))}/><button type="button" className="icon-button" aria-label={`Remove specification ${i+1}`} onClick={()=>change("specs",(edit.value.specs as Robot["specs"]).filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div>)}</div></>}</fieldset>{formError&&<p className="error-text" role="alert">{formError}</p>}<div className="form-footer"><button className="button" type="button" disabled={busy} onClick={()=>setEdit(null)}>Cancel</button><button className="button dark" disabled={busy||!store.isAdmin}>{busy?"Saving…":store.isAdmin?"Save changes":"Administrator access required"}</button></div></form>}</DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={open=>{if(!open&&!busy)setDeleting(null);}}><AlertDialogContent><AlertDialogTitle>Delete {deleting?.name}?</AlertDialogTitle><AlertDialogDescription>This removes the profile from the database and website. This cannot be undone.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep profile</AlertDialogCancel><button className="button delete-button" disabled={busy} onClick={async()=>{if(!deleting)return;setBusy(true);try{await store.erase(deleting.kind,deleting.id);setDeleting(null);toast.success("Profile deleted.");}catch(e){toast.error(e instanceof Error?e.message:"Delete failed.");}finally{setBusy(false);}}}>{busy?"Deleting…":"Delete profile"}</button></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
