"use client";
import {useEffect,useState} from "react";
import {Box,Plus,Users} from "lucide-react";
import {Header,Footer,Photo,Specs} from "@/components/cubic-ui";
import {useCubic} from "@/components/cubic-data";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import type {Robot} from "@/lib/content";
export default function Home(){
 const {robots,members,alumni,mode,error}=useCubic();const [selected,setSelected]=useState<Robot|null>(null);
 const featured=robots.filter(r=>r.featured),others=robots.filter(r=>!r.featured);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{context.registerTool({name:"list_cubic_robots",description:"Read the robot profiles currently shown on Cubic's homepage.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw Error("Expected an empty object.");return {mode,robots};}},{signal:lifecycle.signal});context.registerTool({name:"open_cubic_robot",description:"Open an existing robot's specification panel; does not edit or save data.",inputSchema:{type:"object",properties:{id:{type:"string"}},required:["id"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length!==1||typeof (input as {id:unknown}).id!=="string")throw Error("Expected a robot id.");const robot=robots.find(r=>r.id===(input as {id:string}).id);if(!robot)throw Error("Robot not found.");setSelected(robot);return {opened:robot.id,name:robot.name};}},{signal:lifecycle.signal});}catch{}return()=>lifecycle.abort();},[robots,mode]);
 return <><Header/><main><section className="hero wrap"><div className="eyebrow">FIRST TECH CHALLENGE / TEAM CUBIC</div><h1>“It worked<br/><span>five minutes ago.”</span></h1><div className="hero-bottom"><p>We turn curiosity into code, ideas into mechanisms,<br className="desktop"/> and a collection of parts into something extraordinary.</p><a className="button dark" href="#robots">Explore our robots</a></div><div className="hero-index">DESIGN. BUILD. ITERATE.</div></section>
 <section id="robots" className="wrap robots-section"><div className="section-top"><div><div className="eyebrow">01 / ENGINEERED BY US</div><h2>Meet the machines.</h2></div><span className="section-note">Built to solve. Refined to compete.</span></div>
 {mode==="error"?<div className="notice error" role="alert">Robot profiles are temporarily unavailable. Please try again later.<details><summary>Connection details</summary>{error}</details></div>:mode==="loading"?<p role="status">Loading the robot lab…</p>:<>
 {featured.map(robot=><article className={`featured ${robot.image?"":"without-photo"}`} key={robot.id}>{robot.image&&<div className="robot-stage"><Photo key={robot.image} src={robot.image} alt={`${robot.name} robot`}/><span className="stage-caption">CUBIC / {robot.season||"ROBOT LAB"}</span><span className="image-index">0{robots.indexOf(robot)+1}</span></div>}<div className="robot-copy"><span className="pill">FEATURED ROBOT</span><h3>{robot.name}</h3><p>{robot.description}</p><Specs robot={robot}/><button className="text-button" onClick={()=>setSelected(robot)}><Plus size={16}/> Explore the build</button></div></article>)}
 {others.length>0&&<div className="robot-list">{others.map((robot)=><article className="robot-row" key={robot.id}>{robot.image&&<div className="robot-row-icon"><Photo src={robot.image} alt={robot.name}/></div>}<div className="robot-row-title"><span className="eyebrow">{robot.season||"CUBIC ROBOT"}</span><h3>{robot.name}</h3></div><p>{robot.description}</p><button className="button" onClick={()=>setSelected(robot)}>View specifications</button></article>)}</div>}
 {!robots.length&&<div className="empty-state"><Box/><p>No robots published yet.</p></div>}</>}
 </section><section className="wrap team-section" id="team"><div className="team-heading"><div><div className="eyebrow">02 / THE PEOPLE BEHIND THE PARTS</div><h2>Different minds.<br/>One team.</h2></div><p>Builders, programmers, and creative thinkers.<br/>Together, we are Cubic.</p></div>
 {mode==="error"?<p role="alert">Team profiles are temporarily unavailable.</p>:mode==="loading"?<p role="status">Loading the team…</p>:<><div className="member-grid">{members.map((m)=><article className="member-card" key={m.id}>{m.image&&<div className="member-avatar"><Photo key={m.image} src={m.image} alt={m.name}/></div>}<h3>{m.name}</h3><span className="member-role">{m.role}</span><p>{m.bio}</p></article>)}</div><section className="alumni-section" aria-labelledby="alumni-title"><div><div className="eyebrow">03 / PART OF OUR STORY</div><h2 id="alumni-title">Cubic alumni.</h2><p>Builders and thinkers who helped shape the team.</p></div>{alumni.length?<div className="member-grid alumni-grid">{alumni.map((m)=><article className="member-card" key={m.id}>{m.image&&<div className="member-avatar"><Photo key={m.image} src={m.image} alt={m.name}/></div>}<h3>{m.name}</h3><span className="member-role">{m.role}</span><p>{m.bio}</p></article>)}</div>:<p className="alumni-empty">Alumni profiles coming soon.</p>}</section></>}
 {mode==="live"&&!members.length&&<div className="empty-state"><Users/><p>No members published yet.</p></div>}
 </section><div className="team-band wrap"><Box size={32}/><p>Every great robot starts with a good team.</p><span>THINK IN THREE DIMENSIONS.</span></div>
 </main><Footer/><Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="robot-dialog"><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?.season||"Cubic robot specifications"}</DialogDescription>{selected&&<><p>{selected.description}</p>{selected.image&&<Photo src={selected.image} alt={selected.name} className="detail-image"/>}<dl className="detail-specs">{[["Dimensions",selected.dimensions],["Weight",selected.weight],["Programming",selected.programming],["Materials",selected.materials],["Drivetrain",selected.drivetrain],...selected.specs.map(s=>[s.label,s.value])].filter(([,v])=>v).map(([k,v],i)=><div key={i}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></>}</DialogContent></Dialog></>;
}
